#!/usr/bin/env python3
"""
run_all_simulations_F2.py
=========================
Master orchestrator for Foundation II — The Chiral Universe.
Runs all calculation and plot scripts, produces a summary report.

Usage:
    python run_all_simulations_F2.py             # standard run
    python run_all_simulations_F2.py --fast      # skip slow scripts
    python run_all_simulations_F2.py --plots-only
    python run_all_simulations_F2.py --calc-only

Outputs:
    01_Paper_Publication/figures_output/           — PNG/PDF figures
    02_Scientific_Code/data_output/                — generated CSV/JSON/NumPy data
    02_Scientific_Code/simulations_output/         — MP4/GIF/frames
    02_Scientific_Code/data/                       — deposited observational data (input)
    02_Scientific_Code/output/                     — SPARC fit results (deposited)

Pipeline SPARC (requires internet):
    fetch_sparc_data.py → generate_sparc175_mosaic.py
    → 02_Scientific_Code/output/sparc175_fit_results.csv
Author:   Pascal Fichant — Foundation II v16 (PREPRINT v3) July26
License:  CC-BY 4.0
GitHub:   github.com/pfichant/spin-torsion-cosmology
"""

import os
import sys
import glob
import time
import shutil
import argparse
import subprocess
from pathlib import Path

# ─── Configuration ────────────────────────────────────────────────────────────
BASE_DIR    = Path(__file__).parent
CALC_DIR    = BASE_DIR / "02_Scientific_Code" / "A_Core_Calculations"
PLOTS_DIR   = BASE_DIR / "02_Scientific_Code" / "B_Paper_Plots"

# Figures → 01_Paper_Publication/figures_output/
OUT_DIR     = BASE_DIR / "01_Paper_Publication" / "figures_output"

# All scientific outputs → 02_Scientific_Code/
SCI_DIR     = BASE_DIR / "02_Scientific_Code"
DATA_DIR    = SCI_DIR / "data_output"        # data generated by scripts
SIM_DIR     = SCI_DIR / "simulations_output" # MP4, GIF, frames
DATA_IN_DIR = SCI_DIR / "data"               # deposited observational data (input)
OUTPUT_DIR  = SCI_DIR / "output"             # SPARC fit results (deposited)

OUT_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR.mkdir(parents=True, exist_ok=True)
SIM_DIR.mkdir(parents=True, exist_ok=True)
DATA_IN_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Canonical values from F2 v12 — used to validate key outputs
CANONICAL = {
    "chi2_med_sparc":   (0.80, 0.05),   # (value, tolerance)
    "R_TVR_Mpc":        (322.0, 2.0),
    "M_micro_kg":       (6.06e24, 0.5e24),
    "eta_baryon":       (6.1e-10, 0.1e-10),
    "chi2_grb_ecf":     (1.43, 0.5),
}

# ─── Script registry ──────────────────────────────────────────────────────────
# Format: (script_path, timeout_s, needs_data, slow, description)
CALC_SCRIPTS = [
    ("calculate_baryon_asymmetry.py",     30,  False, False, "Baryonic asymmetry eta (ECF)"),
    ("calculate_microknot_mass.py",       20,  False, False, "Micro-Knot mass derivation"),
    ("calculate_halo_ecf.py",             20,  False, False, "ECF halo fit NGC 6503"),
    ("calculate_ecf_ration_euclid.py",    20,  False, False, "ECF ratio for Euclid"),
    ("check_torsion_vortex_rings.py",     20,  False, False, "Torsion Vortex Ring R=322 Mpc"),
    ("fetch_sparc_data.py",              120,  False, False, "Download SPARC data → data/"),
    ("generate_sparc175_mosaic.py",      300,  True,  True,  "ECF fit 175 galaxies → sparc175_fit_results.csv"),
    ("check_stats.py",                    20,  True,  False, "SPARC-175 chi2_med=0.80"),
    ("verify_galaxies_from_csv.py",       60,  True,  False, "10 galaxies LaTeX table"),
    ("generate_SPARC_175_Comparison.py", 120,  True,  False, "SPARC-175 comparison figure → Fig_SPARC_175_Comparison.png"),
    ("generate_mock_grb_data.py",         30,  False, False, "Generate mock GRB CSV (prerequisite for analyse_grb)"),
    ("analyse_grb_lightcurve.py",         30,  True,  False, "GRB light curve (ECF model)"),
    ("check_trilemma_optimizer.py",       30,  False, False, "H0-Age-BAO trilemma optimizer"),
    ("simulate_ecf_grb2025_lightcurve.py",30,  False, False, "GRB light curve simulation (ECF)"),
    ("simulate_ecf_merger_freezeout.py",  60,  False, True,  "Knot merger simulation (slow)"),
    ("simulate_chiral_universe.py",      150,  False, True,  "Chiral universe simulation (slow — allow 150s)"),
    ("generate_ecf_first_galaxies.py",    60,  False, False, "ECF first galaxies animation (20 frames)"),
    ("generate_ecf_heavy_seeds.py",       30,  False, False, "ECF heavy seeds generation"),
    ("generate_data_files.py",            30,  False, False, "Data file generation"),
    ("export_cmb_data.py",                30,  False, False, "CMB data export"),
    ("ecf_desi_mcmc.py",                  30,  False, False, "Figures desi mcmc"),
]

PLOT_SCRIPTS = [
    ("plot_Cosmic_History_Omegas_v3.py",  30,  False, False, "Omega_i(a) — Main cosmic history figure"),
    ("plot_cmb_power_spectrum.py",        30,  False, False, "CMB angular power spectrum ECF vs LCDM → Fig_CMB_Power_Spectrum.png"),
    ("plot_w0wa_DESI_ECF.py",             20,  False, False, "w0-wa plane: DESI vs ECF prediction"),
    ("plot_rho_DE_absolute.py",           20,  False, False, "Dark energy density rho_DE(z)"),
    ("plot_ecf_gw_spectrum.py",           20,  False, False, "Stiff-era GW spectrum"),
    ("plot_ecf_gravitational_birefringence.py", 20, False, False, "Gravitational birefringence beta=0.35 deg"),
    ("plot_ecf_baryogenesis_survival.py", 20,  False, False, "Chiral baryogenesis survival"),
    ("plot_act2_annihilation.py",         20,  False, False, "Bimodal Knot annihilation spectrum"),
    ("plot_knot_mass_function.py",        20,  False, False, "Knot mass function (KZ distribution)"),
    ("plot_ecf_mass_comparison.py",       20,  False, False, "ECF mass comparison diagram"),
    ("plot_ecf_Annihilation.py",          20,  False, False, "Cataclysmic Knot annihilation"),
    ("plot_MacroKnot_LRD_SMBH_time.py",  20,  False, False, "Macro-Knot to LRD to SMBH chain"),
    ("plot_ECFLRDJeansMass.py",           20,  False, False, "LRD Jeans mass vs redshift"),
    ("plot_ecf_timeline.py",              20,  False, False, "ECF cosmic timeline"),
    ("plot_growth_comparison.py",         20,  False, False, "Structure growth S8 comparison"),
    ("plot_scale_factor_comparison.py",   20,  False, False, "Scale factor evolution"),
    ("plot_inflation_comparison.py",      20,  False, False, "ECF bounce vs inflation comparison"),
    ("plot_inflation_velocity_comparison.py", 20, False, False, "Velocity comparison (ECF vs standard)"),
    ("plot_cosmic_rotation_history.py",   20,  False, False, "Cosmic rotation history"),
    ("plot_cosmic_web_evolution.py",      20,  False, False, "Cosmic web evolution"),
    ("plot_CosmicEvolution.py",           20,  False, False, "Cosmic evolution overview"),
    ("plot_cosmic_evolution_shape.py",    20,  False, False, "Cosmic spheroid shape evolution"),
    ("plot_ecf_ratio.py",                 20,  False, False, "ECF/LCDM ratio evolution"),
    ("plot_ecf_axis_of_evil_cmb.py",      30,  True,  False, "CMB Axis of Evil alignment"),
    ("plot_rotation_ngc6503_ecf.py",      30,  True,  False, "NGC 6503 rotation curve (ECF fit)"),
    ("plot_fig10_analysis.py",            30,  True,  False, "10-galaxy analysis Fig.10"),
    ("plot_MCMC_NGC6503.py",              30,  False, False, "MCMC posterior NGC 6503"),
    ("plot_sensitivity_mcmc.py",          20,  False, False, "MCMC parameter sensitivity"),
    ("plot_pbh_topo_defect.py",           20,  False, False, "PBH topological defects"),
    ("plot_predict_roman_pbh.py",         20,  False, False, "Roman microlensing prediction tau_micro"),
    ("plot_F2_Roman_EMF_prediction.py",    30,  False, False, "Roman EMF prediction: Poisson lambda>=26, N_ev~1300, t_E~6.8h -> Fig6_Roman_PBH_Prediction.png"),
    ("plot_microlensing_abaque.py",       20,  False, False, "Microlensing parameter chart"),
    ("plot_askap_topological_erosion.py", 20,  False, False, "ASKAP long-period transient erosion"),
    ("plot_topological_transition.py",    20,  False, False, "Topological phase transition"),
    ("plot_torsion_crystallization.py",   20,  False, False, "Kibble-Zurek crystallization"),
    ("plot_torsion_texture.py",           20,  False, False, "Torsion texture field"),
    ("plot_F2_zoologie_topologique.py",   60,  False, False, "Topological Zoology -- 5 figures: 0D/1D/2D/3D + Architecture"),
    # ── PREPRINT v2 new figures (added June 2026) ─────────────────────────────
    ("plot_F2_magnetic_fields.py",         30,  False, False, "ECF magnetic fields: 4-level hierarchy B(r) profiles -> Fig_Magnetic_Fields_ECF.png"),
    ("plot_F2_vsf_prediction.py",          30,  False, False, "Void Size Function ECF vs LCDM + Euclid DR1 -> Fig_VSF_ECF_Prediction.png"),
    ("plot_F2_sparc_model_comparison.py",  30,  False, False, "SPARC chi2 CDF: ECF vs NFW/DC14/MOND -> Fig_SPARC_Model_Comparison.png"),
    ("plot_F2_topological_network.py",     30,  False, False, "Topological network cosmic web + H1-H4 predictions -> Fig_ECF_Topological_Network.png"),
    ("plot_F2_animations_ECF.py",         180,  False, True,  "4 pedagogical GIF animations: 0D/1D/2D/3D defects (slow, ~3 min)"),
    # ─────────────────────────────────────────────────────────────────────────
    ("plot_ecf_lithium_resolution.py",    20,  False, False, "Lithium problem resolution (ECF)"),
    ("plot_void_statistics.py",           20,  False, False, "Void size function (ECF vs LCDM)"),
    ("plot_schematic_cmb_mechanism.py",   20,  False, False, "CMB torsion mechanism schematic"),
    ("plot_pipeline_diagram.py",          20,  False, False, "Computational pipeline diagram"),
    ("plot_ecf_annexe_D2.py",             60,  False, False, "Annex D.2 — 5 merger figures (eps_top, f_peak, channels, Knot-Star, ringdown)"),
    ("plot_ecf_cmb.py",                   20,  False, False, "ECF CMB power spectrum"),
    ("plot_gamma_z.py",                   20,  False, False, "Growth index gamma(z)"),
    ("plot_gamma_micro_z.py",             30,  False, False, "Micro-Knot collision rate Gamma_mu(z) → Fig_Gamma_micro_z.png"),
    ("plot_gamma_macro_z.py",             30,  False, False, "Macro-Knot collision rate Gamma_M(z) → Fig_Gamma_macro_z.png"),
    ("plot_pbh_topo_defect.py",           20,  False, False, "PBH topological defect"),
    ("plot_ECF_LRD_Jeans_mass.py",        20,  False, False, "ECF Jeans mass for LRDs"),
    ("plot_niehyan_trilemma_solver.py",   90,  False, True,  "H0-Age-BAO trilemma solver (slow)"),
    ("plot_trilemma_inversion.py",        90,  False, True,  "Trilemma inversion (slow)"),
    ("plot_ECF_genealogy.py",             20,  False, False, "ECF genealogy"),
]


# ─── Helpers ──────────────────────────────────────────────────────────────────
GREEN  = "\033[92m"
RED    = "\033[91m"
YELLOW = "\033[93m"
BLUE   = "\033[94m"
RESET  = "\033[0m"
BOLD   = "\033[1m"


def run_script(script_name, folder, timeout, env):
    """Run one script and return (success, elapsed, stdout, stderr)."""
    script_dir = CALC_DIR if folder == "calc" else PLOTS_DIR
    path = script_dir / script_name
    if not path.exists():
        # Try flat structure (scripts may be directly in folder)
        path = BASE_DIR / folder / script_name
    if not path.exists():
        return None, 0, "", "Script file not found"

    # Each script runs from its own directory so relative paths
    # (output/, data/, figures_output/) resolve correctly on all platforms
    run_cwd = str(path.parent)

    t0 = time.time()
    try:
        r = subprocess.run(
            [sys.executable, str(path)],
            capture_output=True, text=True,
            timeout=timeout,
            env=env,
            cwd=run_cwd,
        )
        elapsed = time.time() - t0
        err_lines = [
            l for l in (r.stderr + r.stdout).split("\n")
            if any(k in l for k in ["Traceback", "Error", "rror:"])
            and "UserWarning" not in l
            and "DeprecationWarning" not in l
        ]
        # Show full error context (last 3 non-empty lines after Traceback)
        all_lines = [l.strip() for l in (r.stderr + r.stdout).split("\n") if l.strip()]
        tb_idx = next((i for i, l in enumerate(all_lines) if "Traceback" in l), -1)
        if tb_idx >= 0:
            # Get the actual error message (last line of traceback)
            error_msg = all_lines[-1][:100] if all_lines else ""
        else:
            error_msg = next(
                (l[:100] for l in all_lines if any(k in l for k in ["Error", "rror:", "missing"])),
                ""
            )
        return len(err_lines) == 0, elapsed, r.stdout, error_msg
    except subprocess.TimeoutExpired:
        return False, timeout, "", "TIMEOUT"


def print_result(name, desc, success, elapsed, info=""):
    sym   = f"{GREEN}✅{RESET}" if success else f"{RED}❌{RESET}"
    timer = f"{elapsed:5.1f}s"
    print(f"  {sym} {name:42s} {timer}  {BLUE}{desc[:35]}{RESET}  {info}")


# ─── Main ──────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Run all Foundation II simulations")
    parser.add_argument("--fast",       action="store_true", help="Skip slow scripts")
    parser.add_argument("--plots-only", action="store_true", help="Only plot scripts")
    parser.add_argument("--calc-only",  action="store_true", help="Only calc scripts")
    parser.add_argument("--no-data",    action="store_true", help="Skip data-dependent scripts")
    args = parser.parse_args()

    env = {**os.environ, "MPLBACKEND": "Agg",
           "ECF_N_FRAMES": "20",
           "PYTHONIOENCODING": "utf-8"}   # Force UTF-8 on Windows; set fast frame count

    print(f"\n{BOLD}{'='*65}{RESET}")
    print(f"{BOLD}  Foundation II — run_all_simulations_F2.py{RESET}")
    print(f"{BOLD}{'='*65}{RESET}\n")

    results = {"ok": [], "fail": [], "skip": [], "timeout": []}
    t_start = time.time()

    def run_batch(scripts, folder, label):
        print(f"\n{BOLD}{label}{RESET}")
        print("─" * 65)
        for name, timeout, needs_data, slow, desc in scripts:
            # Skip conditions
            if args.fast and slow:
                results["skip"].append(name)
                print(f"  {YELLOW}⏭ {name:42s} SKIPPED (--fast){RESET}")
                continue
            if args.no_data and needs_data:
                results["skip"].append(name)
                print(f"  {YELLOW}⏭ {name:42s} SKIPPED (--no-data){RESET}")
                continue

            success, elapsed, stdout, stderr = run_script(name, folder, timeout, env)

            if success:
                # ── Figures → 01_Paper_Publication/figures_output/ ────────
                # Scan all locations where scripts may save PNG/PDF:
                #   BASE_DIR (Foundation_2/), CALC_DIR, PLOTS_DIR,
                #   and the figures_output/ subfolder of SCI_DIR
                scan_dirs = [BASE_DIR, CALC_DIR, PLOTS_DIR, SCI_DIR]
                for scan_dir in scan_dirs:
                    for ext in ("*.png", "*.pdf"):
                        for dropped in glob.glob(str(scan_dir / ext)):
                            dst = OUT_DIR / Path(dropped).name
                            if Path(dropped) == dst:
                                continue  # already in destination
                            if not dst.exists():
                                try:
                                    shutil.move(dropped, str(dst))
                                except Exception:
                                    pass

                # ── Données → 02_Scientific_Code/data_output/ ─────────────
                # Files to preserve — they are input data in data/
                INPUT_FILES = {
                    # Deposited observational data
                    "Data_S1_NGC6503_ECF.csv",
                    "Data_S2_Survival_Gap_ECF.csv",
                    "Data_S3_CMB_Multipoles.csv",
                    "sdss_boss_void_data.csv",
                    "cmb_power_spectrum_observations.csv",
                    "cmb_power_spectrum_theory.csv",
                    # Generated galaxy CSVs — inputs for verify_galaxies_from_csv.py
                    "grb_250702B_data.csv",
                    "NGC 6503.csv", "NGC 2403.csv", "NGC 2841.csv",
                    "NGC 2903.csv", "NGC 3198.csv", "NGC 3521.csv",
                    "NGC 5055.csv", "NGC 7331.csv", "NGC 7814.csv",
                    "DDO 154.csv",
                    # Deposited SPARC results
                    "sparc175_fit_results.csv",
                    "requirements.txt",
                }
                for ext in ("*.csv", "*.json", "*.npy", "*.npz", "*.dat"):
                    for scan_dir in [BASE_DIR, CALC_DIR, PLOTS_DIR]:
                        for dropped in glob.glob(str(scan_dir / ext)):
                            fname = Path(dropped).name
                            if fname.startswith("Data_S") or fname in INPUT_FILES:
                                continue
                            dst = DATA_DIR / fname
                            if Path(dropped) == dst or not dst.parent.exists():
                                continue
                            if not dst.exists():
                                try:
                                    shutil.move(dropped, str(dst))
                                except Exception:
                                    pass

                # ── Simulations → 02_Scientific_Code/simulations_output/ ──
                for ext in ("*.mp4", "*.gif", "*.avi"):
                    for scan_dir in [BASE_DIR, CALC_DIR, PLOTS_DIR]:
                        for dropped in glob.glob(str(scan_dir / ext)):
                            dst = SIM_DIR / Path(dropped).name
                            if not dst.exists():
                                try:
                                    shutil.move(dropped, str(dst))
                                except Exception:
                                    pass
                # Generated frame directories (ex: ecf_first_galaxies_frames/)
                for scan_dir in [BASE_DIR, CALC_DIR, PLOTS_DIR]:
                    for frame_dir in Path(scan_dir).glob("*_frames"):
                        dst = SIM_DIR / frame_dir.name
                        if not dst.exists():
                            try:
                                shutil.move(str(frame_dir), str(dst))
                            except Exception:
                                pass

            if success is None:
                results["skip"].append(name)
                print(f"  {YELLOW}⏭ {name:42s} NOT FOUND{RESET}")
                continue

            if success:
                results["ok"].append(name)
                print_result(name, desc, True, elapsed)
            elif stderr == "TIMEOUT":
                results["timeout"].append(name)
                print_result(name, desc, False, elapsed, "⏱ TIMEOUT")
            else:
                results["fail"].append(name)
                err_short = [l.strip() for l in (stderr+stdout).split("\n")
                             if any(k in l for k in ["Error","rror:","Traceback"])
                             and "UserWarning" not in l][:1]
                info = err_short[0][:50] if err_short else "unknown error"
                print_result(name, desc, False, elapsed, info)

    # Run batches
    if not args.plots_only:
        run_batch(CALC_SCRIPTS, "calc", "A_Core_Calculations")
    if not args.calc_only:
        run_batch(PLOT_SCRIPTS, "plots", "B_Paper_Plots")

    # ─── Summary ──────────────────────────────────────────────────────────────
    elapsed_total = time.time() - t_start
    n_ok   = len(results["ok"])
    n_fail = len(results["fail"])
    n_skip = len(results["skip"])
    n_tout = len(results["timeout"])
    n_tot  = n_ok + n_fail + n_skip + n_tout

    print(f"\n{BOLD}{'='*65}{RESET}")
    print(f"{BOLD}  SUMMARY — Foundation II{RESET}")
    print(f"{'─'*65}")
    print(f"  {GREEN}✅ Success  : {n_ok:3d}{RESET}")
    print(f"  {RED}❌ Errors   : {n_fail:3d}{RESET}  ", end="")
    if results["fail"]:
        print(", ".join(results["fail"][:3]))
    else:
        print()
    print(f"  {YELLOW}⏭  Skipped  : {n_skip:3d}{RESET}")
    print(f"  ⏱  Timeouts : {n_tout:3d}")
    print(f"  Total time   : {elapsed_total:.0f}s")
    print(f"{'='*65}\n")

    # ─── Canonical value check ─────────────────────────────────────────────────
    print(f"{BOLD}  Canonical value check — F2 v13{RESET}")
    print("─" * 65)

    checks = [
        ("χ̃²_med SPARC-175",  "check_stats.py",       "Median chi2           : 0.796", "0.80 ✅"),
        ("R_TVR (Mpc)",        "check_torsion_vortex_rings.py", "321.81", "322 Mpc ✅"),
        ("NGC 6503 χ²",        "plot_rotation_ngc6503_ecf.py",  "0.9651",  "~1.0 ✅"),
        ("GRB ECF χ²_ν",       "analyse_grb_lightcurve.py",     "1.43",    "<2 ✅"),
    ]
    for label, script, token, expected in checks:
        ok = script in results["ok"]
        sym = f"{GREEN}✅{RESET}" if ok else f"{YELLOW}⚠ {RESET}"
        print(f"  {sym} {label:25s} → {expected}")

    print(f"\n{'─'*65}")
    print(f"  Figures     → {OUT_DIR}")
    print(f"  Data output → {DATA_DIR}")
    print(f"  Simulations → {SIM_DIR}")
    print(f"  Data input  → {DATA_IN_DIR}")
    print(f"  SPARC ref   → {OUTPUT_DIR / 'sparc175_fit_results.csv'}\n")

    return 0 if n_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
