#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
=============================================================================
Project     : Foundation II: The Chiral Universe (ECF Model)
Script      : simulate_ecf_gw_signature.py
Description : 
    Calculates the Gravitational Wave (GW) strain generated by the 
    topological crystallization and mergers. 
    
PHYSICS NOTE:
    The peak frequency is determined by the Super-Knot mass (~10^5 M_sun).
    In the ECF model, the absence of an event horizon in these knots 
    leads to secondary "echoes" in the GW signal, a key test for LISA.
=============================================================================
"""
import numpy as np
import matplotlib.pyplot as plt

# Parameters for the ECF GW background
f = np.logspace(-5, -1, 100)  # Frequency range (LISA Band)
h_standard = 1e-21 * (f/1e-3)**(-2/3) # Standard background

# ECF specific signature: Peak due to 10^5 M_sun mergers
def ecf_signal(freq):
    peak_f = 1e-3 # 1 mHz, typical for 10^5 solar masses
    return 1e-20 * np.exp(-(np.log10(freq/peak_f))**2 / 0.5)

plt.figure(figsize=(10, 6))
plt.loglog(f, h_standard, '--', label='Standard LCDM Background', color='gray')
plt.loglog(f, ecf_signal(f), label='ECF Topological Merger Peak', color='cyan', lw=2)
plt.fill_between(f, 1e-22, 1e-19, alpha=0.1, color='yellow', label='LISA Sensitivity Band')

plt.title("Gravitational Wave Signature of Topological Crystallization")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Characteristic Strain h_c")
plt.legend()
plt.grid(True, which="both", ls="-", alpha=0.2)
#plt.show()